### ISSUE TITLE
Validate data given as array

### ISSUE THREAD

**Issue by Awkan** [biig-io/DictionaryBundle#25]
# Problem

- I have an array field
- I am using a DictionaryType with `multiple => true`
- Validation with `DictionaryValidator`

During the validation step, I encounter the error "Array to string conversion". That's because my data are formatted as array. 

# Solution

- Update Validator in order to accept array data. Validate each values in array
- Create a Validator for array

**Comment by Nek-** [comment]
Oh, you mean the DictionaryValidator fails with `multiple` option of the type? That's not great indeed.
