### ISSUE TITLE
[RFC] Ability to deal with "categories"

### ISSUE THREAD

**Issue by Nek-** [biig-io/DictionaryBundle#27]
**Problem:** The current registry is quite simple but in complex applications, we use to have many dictionaries. The possibility to have a tree for splitting dictionaries in categories and subcategories would be a great improvement.

**Solution:** I suggest to add a new kind of registry and the notion of "category".

**Comment by Awkan** [comment]
Create a `CategoryDictionary` seems to be the good idea !

**Comment by Valouleloup** [comment]
Can you provide a use case ?

**Comment by Nek-** [comment]
I don't think a "CategoryDictionary" is a good idea. The problem is more complexe and imply a registry and a new "category" notion.

Here is a use case:

> I have a Toy as product. I distribute this Toy to some *vendor*, and have a vendor dictionary. "auchan", "monoprix", "la grande récré"
> But for the second product, my vendors are "bricomarket", "bricodiscount" and "bricoswagg".

I have 2 dictionaries that have a "category" (the product). This may happen with many "fields" of the products that looks similar but are completely different.

Here is another use case:
> I have a roles dictionary. But it would be better to split them by responsability.

What do you think @Valouleloup ?

**Comment by Valouleloup** [comment]
Hm, well-organized dictionaries into directories seems enough to me. I don't think categories will bring any added value for this use case.

IMO, categories could be interesting if you want to search all dictionaries that are 'Toy-related', 'vendor-related', etc.. for example.
