### ISSUE TITLE
[RFC] One category is nice. Many categories is awesome.

### ISSUE THREAD

**Issue by Nek-** [biig-io/DictionaryBundle#34]
The alpha version of the dictionary bundle supports 1 category. I think supporting many categories is a must-have for this kind of feature because the system is more like a tag system.

Also I suggest to rename it "tag" while the dictionary is still in alpha phase. What do you think of that?

cc @Awkan @valentin-biig @athos7933 @babeou

**Comment by athos7933** [comment]
Fully agree with you @Nek-

**Comment by babeou** [comment]
I agree too
